name = "ens-gateway"
main = "src/index.ts"
compatibility_date = "2023-03-15"

kv_namespaces = [
  { binding = "RECORDS", id = "a96ae7c81e4a4507a83fcdf8316eb12f", preview_id = "176b9d2f873d4af282d93c0e94da8e42" },
]

[vars]
IS_TEMPORARY=true

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
